###############################################################
# National Supercomputing Consortium
#
# Configuration File for UNIVERSITY 1
#
# Every machine runs the SAME Java program.
# Only this configuration file changes.
#
# This file tells the program:
#   • Who am I?
#   • Which port do I listen on?
#   • Which university is my parent?
#   • Which universities are my children?
#   • Where are all universities located?
###############################################################

############################
# BASIC INFORMATION
############################

site.id=1
site.name=University-1

host=100.121.48.30
port=5001

total.sites=3
coordinator.id=3
############################
# OTHER UNIVERSITY ADDRESSES
############################

site1.host=100.121.48.30
site1.port=5001

site2.host=100.86.6.119
site2.port=5002

site3.host=100.85.3.115
site3.port=5003



