###############################################################
# National Supercomputing Consortium
#
# Configuration File for UNIVERSITY 1
#
# Every machine runs the SAME Java program.
# Only this configuration file changes.
#
# This file tells the program:
#   • Who am I?
#   • Which port do I listen on?
#   • Which university is my parent?
#   • Which universities are my children?
#   • Where are all universities located?
###############################################################

############################
# BASIC INFORMATION
############################

site.id=1

site.name=University-1

host=100.121.48.30

port=5001
total.sites=4
coordinator.id=1
############################
# OTHER UNIVERSITY ADDRESSES
############################

site1.host=100.121.48.30 //sayan
site1.port=5001

#site2.host=100.86.6.119 //sampurna
#site2.port=5002

#site3.host=100.89.173.7 //suhana
#site3.port=5003

site4.host=100.85.3.115 //debjit
site4.port=5004

