site.id=2
site.name=University-2

host=100.86.6.119
port=5002

total.sites=3
coordinator.id=3
############################
# OTHER UNIVERSITY ADDRESSES
############################

site1.host=100.121.48.30
site1.port=5001

site2.host=100.86.6.119
site2.port=5002

site3.host=100.85.3.115
site3.port=5003